### ISSUE TITLE
關於運行錯誤

### ISSUE THREAD

**Issue by Mmc1xs** [SchneeHertz/chat-xiuliu#1]
作者你好 我根據您的提是調整了在utils的initFile.js的內容
填入了OPENAI的API金鑰以及Azure的API金鑰
安裝好程序之後我執行了專案 但是跳出了以下錯誤訊息 請問您有頭緒嗎?

$ npm start
(node:28120) electron: Failed to load URL: http://localhost:5173/ with error: ERR_CONNECTION_REFUSED
(Use `electron --trace-warnings ...` to show where the warning was created)

**Comment by SchneeHertz** [comment]
如果你没有特别需要，安装后运行，不需要修改除了config.json的其他文件
开发环境需要先启动vite服务，再启动electron
```
npm run dev  
npm run start
```

**Comment by Mmc1xs** [comment]
原來是要開兩個程序才會正常運行...
難怪會卡住 謝謝
不過我的API額度也用光了 等明天更新額度後我再來試試看

**Comment by Dxcyc9** [comment]
你好，我安装了程序之后，将配置环境也都安装好了。但我open config按键点击后打不开配置文件，我自己找到config.json进行修改key后，进行发送消息，xiuliu仍不能进行消息返回。且我的speech off点击后电脑能显示在录音，但聊天框不能识别我刚刚说的话。想问问这是为什么

**Comment by SchneeHertz** [comment]
> 你好，我安装了程序之后，将配置环境也都安装好了。但我open config按键点击后打不开配置文件，我自己找到config.json进行修改key后，进行发送消息，xiuliu仍不能进行消息返回。且我的speech off点击后电脑能显示在录音，但聊天框不能识别我刚刚说的话。想问问这是为什么

修改config后要重启程序才能生效，如果还不行，检查一下麦克风是否正常工作

**Comment by Dxcyc9** [comment]
> 

不太行啊，修改了config后，我继续发消息还是没有回复。麦克风正常，但识别不了说的话
